### ISSUE TITLE
VS. Mode Black Screen

### ISSUE THREAD

**Issue by TheMasterCreed** [XenesisXenon/AW2-InfiniteCOs#20]
If I assimilate the file using compile.asm without changing anything in any of the assembly files, the game starts up fine etc. except when I try to open a vs. mode map I just get sent to a black screen and get soft locked there. Is there anything I need to change before compiling the rom?

**Comment by XenesisXenon** [comment]
First thing is to check whether you have a clean AW2 (U) ROM, if you start with the fancrack one with the modified intros it may fail in weird ways.

Otherwise, I think there's something I need to investigate.

Does everything else work fine?

**Comment by TheMasterCreed** [comment]
Everything else does work fine, I made sure to have a clean ROM, I tried
the cleaner patch as well. Campaign mode, War room, all works fine. I just
get soft locked on a black screen when I try to open a vs. mode map.

**Comment by XenesisXenon** [comment]
Alright, looks like I've got some investigating to do. Suspect I know where to start looking - thanks for your report.

**Comment by TheMasterCreed** [comment]
No problem!
