### ISSUE TITLE
Erroneous CO Power Charge fill values

### ISSUE THREAD

**Issue by TheMasterCreed** [XenesisXenon/AW2-InfiniteCOs#21]
Star power immediately makes the star power gauge fill completely for both CO's.  APC boost has no effect. Just let me know if you want me to keep playtesting because I'll keep reporting! Haven't tested much of the skills yet but those are the two that are easily noticeable. I haven't changed any of the assembly settings so if it's just something I have to edit just let me know.

**Comment by TheMasterCreed** [comment]
Actually I stand corrected about the co power. It seems two specific CO's cause immediate filling of the CO power meters, Hachi and Collin from AW2. If either one of those CO's are used, the CO powers fill immediately. The AWDS versions seem to function perfectly fine however.

Update: It seems both Hachi and Collin, no matter what Advance Wars you pick them from, just have weird interactions with Power Meters. For example, picking AW2 Collin will have his power meter fill immediately as soon as he gains a small amount of star power, but AWDS Collin will immediately fill up the opponents star power gauge instead of his own gauge. So idk, some weird effects going on with those two CO's.

**Comment by Whattheshmitty** [comment]
![Untitled](https://user-images.githubusercontent.com/85777134/124402557-9c765b80-dcf6-11eb-85ee-20cc1f714ac8.png)
![Untitled2](https://user-images.githubusercontent.com/85777134/124402578-badc5700-dcf6-11eb-9c19-7ebb127c24a0.png)
Still no luck. Checked battle forecast just to make sure the bars were not lying, still no extra defense.

**Comment by TheMasterCreed** [comment]
Isolated the issue, the power bug has nothing to do with skills. What fixes the co powers immediately filling up when using Collin or Hachi is setting the charging type to AWDS charging in the battle maps menu. However, all three other settings, AW2, AW1, and Per CO charging types all have this bug. The only one that doesn't cause this bug is AWDS charging.

**Comment by TheMasterCreed** [comment]
Prairie dog and Pathfinder also do not work. I'm starting to get the feeling that movement skills in general don't work.

**Comment by XenesisXenon** [comment]
Thanks for the update on the bug source - I expected some bugs from the variable charging options but this is not the result I expected XD

Yeah, some of the skills are partially implemented - hence why this isn't at release version

**Comment by TheMasterCreed** [comment]
Afraid I have some bad news, although it is interesting.
So interestingly enough, with ADDS style charging, on Olaf's Navy and Olaf's Sea Strike AD1 maps in VS. mode,  the co powers bars fill completely as soon as you attack, no matter what co you use. I originally thought maybe it had something to do with how high of a map ID I was playing on, but playing a map that comes after Olaf's Sea Strike didn't have the same effect. Not sure if some maps use some specific code that causes this or if the next map even though it comes after in the select menu isn't a higher ID, but I'm not entirely sure. I also tried AW1 charging style on the same two maps and the charging worked perfectly fine when I had that setting on.

I don't feel like testing every map lol but maybe this will shine some light on the bug, or it could be an entirely separate issue, who the heck knows.

PS.
I don't know if you want to slap me or thank me for all of the bugs I've been reporting 😂, but hey if people would realize how valuable play testing is I feel this project could possibly have come along more quickly, or at least more bugs would already be hammered out. At least you have one regular play tester now 😂.

**Comment by XenesisXenon** [comment]
That is indeed very odd that charging breaks on one specific map - but it might help? Weird edge cases have been helping me track down less weird edge cases and other bugs.

PS.
No, I'm really happy that you're finding and reporting bugs! It makes me groan internally because I need to fix them, but it's really valuable. It's a huge project and there's been chunks of time away from it so I don't have a clear idea of what is working 100% and what needs fixes.

**Comment by XenesisXenon** [comment]
>  APC boost has no effect.

This has been implemented with the latest commit

**Comment by XenesisXenon** [comment]
> So interestingly enough, with ADDS style charging, on Olaf's Navy and Olaf's Sea Strike AD1 maps in VS. mode, the co powers bars fill completely as soon as you attack, no matter what co you use. I originally thought maybe it had something to do with how high of a map ID I was playing on, but playing a map that comes after Olaf's Sea Strike didn't have the same effect. Not sure if some maps use some specific code that causes this or if the next map even though it comes after in the select menu isn't a higher ID, but I'm not entirely sure. I also tried AW1 charging style on the same two maps and the charging worked perfectly fine when I had that setting on.

Turns out that it was an issue with Submarines in AWDS mode not having a value (the charge values table was missing an entry, so submarine would grab a charge value of 255).

With that, that should be all the COP charging issues reported in this issue
