### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by TheMasterCreed** [XenesisXenon/AW2-InfiniteCOs#23]
Not sure what this is, it only shows very very briefly, but I managed to catch a screenshot. It cannot read "8x8tiledefinitions.bin".

Not sure if it's an actual issue but just thought I would bring it to your attention anyway.
![Untitled](https://user-images.githubusercontent.com/85777134/124402222-81a2e780-dcf4-11eb-8ff9-d7e57f9e6976.png)

**Comment by XenesisXenon** [comment]
ARMIPS sometimes has issues with system filepaths that have punctuation in it, that might be the issue?

**Comment by TheMasterCreed** [comment]
Changed the filepath folders to have no punctuation. Still no good. Not sure what could be the issue. Is this an isolated problem to me?
![Untitled](https://user-images.githubusercontent.com/85777134/124513152-c6d02380-dd9f-11eb-8628-597fe6b27d55.png)

**Comment by XenesisXenon** [comment]
Hmm, I guess the other thing would be to check that the file is actually there in the filepath.

I don't get that error on compile in my master build.
