### ISSUE TITLE
FE Maps

### ISSUE THREAD

**Issue by TheMasterCreed** [XenesisXenon/AW2-InfiniteCOs#25]
I noticed there are FE Maps in VS. mode. However, they all seem to default to the first classic map. Is this a bug or just an incomplete feature?
![Untitled](https://user-images.githubusercontent.com/85777134/124513374-49f17980-dda0-11eb-8cf9-3018b86c37fa.png)

**Comment by XenesisXenon** [comment]
It's currently incomplete. May or may not keep it because adapting FE maps to AW sucks more than I thought it would.

**Comment by XenesisXenon** [comment]
I've decided that I'm not going to add these in (and with Commit 44d9eeb23684553ec2dbc9b17a4d73ef47483db3 the list is no longer able to be selected) - so in future these refs will slowly be removed. :)
